"""initial schema

Revision ID: 2d45d4681afb
Revises: 
Create Date: 2026-03-02 17:07:19.001234
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d45d4681afb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_encrypted', sa.String(length=500), nullable=True),
    sa.Column('enable_secret_encrypted', sa.String(length=500), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dest_type', sa.Enum('local', 'forgejo', 'smb', name='destinationtype'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('retention_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('devices_total', sa.Integer(), nullable=True),
    sa.Column('devices_success', sa.Integer(), nullable=True),
    sa.Column('devices_failed', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_id'), 'job_runs', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('device_ids', sa.JSON(), nullable=True),
    sa.Column('device_group', sa.String(length=100), nullable=True),
    sa.Column('backup_engine', sa.String(length=50), nullable=True),
    sa.Column('destination_ids', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_type', sa.Enum('ruckus_fastiron', 'cisco_ios', 'cisco_nxos', 'arista_eos', 'juniper_junos', 'generic', name='devicetype'), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('backup_engine', sa.Enum('netmiko', 'scp', 'oxidized', name='backupenginetype'), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('config_text', sa.Text(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('destination_type', sa.String(length=50), nullable=True),
    sa.Column('destination_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', 'unchanged', 'in_progress', name='backupstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retention_tier', sa.String(length=20), nullable=True),
    sa.Column('is_pruned', sa.Boolean(), nullable=True),
    sa.Column('pruned_at', sa.DateTime(), nullable=True),
    sa.Column('job_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_device_id'), 'backups', ['device_id'], unique=False)
    op.create_index(op.f('ix_backups_id'), 'backups', ['id'], unique=False)
    op.create_index(op.f('ix_backups_timestamp'), 'backups', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backups_timestamp'), table_name='backups')
    op.drop_index(op.f('ix_backups_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_device_id'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_job_runs_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
